// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKNgO-PmnGTUQuO2X0QhLC7wvKkXIrGYk',
    appId: '1:997020620472:android:3b2d899fe3b2f362f3864d',
    messagingSenderId: '997020620472',
    projectId: 'cookly-e712f',
    storageBucket: 'cookly-e712f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANs09T2o8CWK6e8MUyWfkXQAyPHfR-fhU',
    appId: '1:997020620472:ios:e0a0a95852591f4ff3864d',
    messagingSenderId: '997020620472',
    projectId: 'cookly-e712f',
    storageBucket: 'cookly-e712f.firebasestorage.app',
    iosBundleId: 'com.example.cookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANs09T2o8CWK6e8MUyWfkXQAyPHfR-fhU',
    appId: '1:997020620472:ios:e0a0a95852591f4ff3864d',
    messagingSenderId: '997020620472',
    projectId: 'cookly-e712f',
    storageBucket: 'cookly-e712f.firebasestorage.app',
    iosBundleId: 'com.example.cookly',
  );
}
